//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drafted
    {
        public int PlayerId { get; set; }
        public int RotoTeamId { get; set; }
        public int PositionId { get; set; }
        public int ActiveFlag { get; set; }
        public decimal Price { get; set; }
        public string TypeYear { get; set; }
        public int KeeperFlag { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Position Position { get; set; }
        public virtual RotoTeam RotoTeam { get; set; }
    }
}
