//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MLBTeam { get; set; }
        public string PosDisp { get; set; }
        public int PosCode { get; set; }
        public int ProjAB { get; set; }
        public int ProjH { get; set; }
        public int ProjHR { get; set; }
        public int ProjRS { get; set; }
        public int ProjRBI { get; set; }
        public int ProjSB { get; set; }
        public int ProjOuts { get; set; }
        public int ProjER { get; set; }
        public int ProjWH { get; set; }
        public int ProjW { get; set; }
        public int ProjSV { get; set; }
        public int ProjK { get; set; }
        public decimal EstValue { get; set; }
        public int Ineligible { get; set; }
        public Nullable<int> TierPos { get; set; }
        public Nullable<int> TierNum { get; set; }
        public Nullable<int> TierRank { get; set; }
        public Nullable<int> TierColor { get; set; }
        public string Notes { get; set; }
        public int RosterCat { get; set; }
    
        public virtual Drafted Drafted { get; set; }
        public virtual MLBTeam MLBTeam1 { get; set; }
    }
}
