//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionAnalysis
    {
        public int PositionId { get; set; }
        public Nullable<int> OpenSlots { get; set; }
        public int CanMove { get; set; }
        public Nullable<int> AuxOpenSlots { get; set; }
        public int AuxCanMove { get; set; }
        public Nullable<int> TotPlayers { get; set; }
        public Nullable<int> AvailPlayers { get; set; }
        public Nullable<int> TopTot { get; set; }
        public Nullable<int> TopAvail { get; set; }
        public Nullable<int> MidTot { get; set; }
        public Nullable<int> MidAvail { get; set; }
        public Nullable<int> LowTot { get; set; }
        public Nullable<int> LowAvail { get; set; }
        public decimal AvailFactor { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
