//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RotoTeam
    {
        public RotoTeam()
        {
            this.Drafteds = new HashSet<Drafted>();
        }
    
        public int RotoTeamId { get; set; }
        public string RotoTeamName { get; set; }
        public int TargetId { get; set; }
        public int Owned { get; set; }
    
        public virtual ICollection<Drafted> Drafteds { get; set; }
        public virtual Target Target { get; set; }
        public virtual RotoTeamPosNeeded RotoTeamPosNeeded { get; set; }
    }
}
